### ISSUE TITLE
find issues

### ISSUE THREAD

**Issue by gustysap** [rioastamal/shdir-listing#2]
Halo mas rio,

Thank you atas opensource codenya, menurut saya ini cukup membantu saya juga yang malas membuat tools script sendiri hehe.

ketika saya coba di device saya menggunakan find version 4.8.0 dan di salah satu server dengan find version 4.5.11. Terdapat issue find dengan output seperti ini.

```
find: warning: you have specified the global option -depth after the argument -type, but global options are not positional, i.e., -depth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: paths must precede expression: `2'
```

Namun dari sisi saya ada mengubah tambahan syntax seperti ini

yang sebelumnya 
```
find $1 -type d -depth $depth | sort
```
menjadi
```
find $1 -maxdepth $depth -type d | sort
```

mengubah semua kata -depth menjadi -maxdepth. Dan issue output tersebut sudah hilang.

Mungkin bisa dibantu cek juga dari sisi mas rio.

**Comment by rioastamal** [comment]
Terima kasih atas laporannya.

Saya kemarin waktu tes kebetulan hanya menggunakan macOS jadinya yang digunakan adalah versi find dari BSD. Sedangkan di Linux mengunakan GNU find. Sepertinya terdapat sedikit perbedaan perilaku disini. Akan saya cek lagi.

**Comment by rioastamal** [comment]
@gustysap silahkan coba lagi. Harusnya sekarang udah fixed di commit 21b24ba893108f4632a1a3b5e2c06f70ae4019ee.

**Comment by gustysap** [comment]
Halo mas @rioastamal ,

Sudah aman nih mas. Terima kasih yak mas atas opensource codenya.

**Comment by rioastamal** [comment]
Sip . Issue akan ditutup.
